# Generated by Django 5.0.2 on 2024-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0003_rename_last_name_company_cik_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cik',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
