# Generated by Django 5.0.2 on 2024-04-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0004_alter_company_cik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company',
            new_name='cik',
        ),
    ]
