# Generated by Django 5.0.2 on 2024-04-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0005_rename_company_companyinfo_cik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='cik',
            field=models.ForeignKey(db_column='cik', on_delete=django.db.models.deletion.CASCADE, to='openedgar.company'),
        ),
    ]
