# Generated by Django 5.0.2 on 2024-04-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0006_alter_companyinfo_cik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='cik',
            field=models.ForeignKey(db_column='cik', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedgar.company', unique=True),
        ),
    ]
