# Generated by Django 5.0.2 on 2024-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0008_remove_companyinfo_state_location_companyfiling_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilingIndex',
        ),
        migrations.RenameField(
            model_name='companyfiling',
            old_name='s3_path',
            new_name='path',
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='acceptance_datetime',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='date_downloaded',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='document_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='homepage_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='processed_document_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyfiling',
            name='text_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
