# Generated by Django 5.0.2 on 2024-12-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0010_companyfiling_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfiling',
            old_name='name',
            new_name='company',
        ),
    ]
