# Generated by Django 5.0.2 on 2024-12-15 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0011_rename_name_companyfiling_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyFiling',
            new_name='Filing',
        ),
        migrations.CreateModel(
            name='FilingIndex',
            fields=[
                ('form_type', models.CharField(db_index=True, max_length=64, null=True)),
                ('company', models.CharField(db_index=True, max_length=1024, null=True)),
                ('date_filed', models.DateField(db_index=True, null=True)),
                ('accession_number', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('cik', models.ForeignKey(db_column='cik', on_delete=django.db.models.deletion.CASCADE, to='openedgar.company')),
            ],
        ),
    ]
