# Generated by Django 5.0.2 on 2024-12-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0012_rename_companyfiling_filing_filingindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfacts',
            name='id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
    ]
