# Generated by Django 5.0.2 on 2024-12-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0013_alter_companyfacts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactIndex',
            fields=[
                ('fact', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='companyfacts',
            name='fact',
            field=models.ForeignKey(db_column='fact', on_delete=django.db.models.deletion.CASCADE, to='openedgar.factindex'),
        ),
    ]
