# Generated by Django 5.0.2 on 2024-12-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0014_factindex_alter_companyfacts_fact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyFacts',
            new_name='CompanyFact',
        ),
    ]
