# Generated by Django 5.0.2 on 2024-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0015_rename_companyfacts_companyfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factindex',
            name='description',
            field=models.CharField(max_length=2048),
        ),
    ]
