# Generated by Django 5.0.2 on 2024-12-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0016_alter_factindex_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factindex',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='factindex',
            name='label',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
