# Generated by Django 5.0.2 on 2024-12-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0017_alter_factindex_description_alter_factindex_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfact',
            name='accession_number',
            field=models.ForeignKey(db_column='accession_number', on_delete=django.db.models.deletion.CASCADE, to='openedgar.filingindex'),
        ),
    ]
