# Generated by Django 5.0.2 on 2024-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0018_alter_companyfact_accession_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormIndex',
            fields=[
                ('form', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('topics', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
