# Generated by Django 5.0.2 on 2024-12-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0019_formindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formindex',
            name='topics',
        ),
        migrations.AlterField(
            model_name='companyfact',
            name='formtype',
            field=models.ForeignKey(db_column='form', max_length=1024, on_delete=django.db.models.deletion.CASCADE, to='openedgar.formindex'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='form_type',
            field=models.ForeignKey(db_column='form', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='openedgar.formindex'),
        ),
        migrations.AlterField(
            model_name='filingindex',
            name='form_type',
            field=models.ForeignKey(db_column='form', null=True, on_delete=django.db.models.deletion.CASCADE, to='openedgar.formindex'),
        ),
    ]
