# Generated by Django 5.0.2 on 2024-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0020_remove_formindex_topics_alter_companyfact_formtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfact',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='companyfact',
            name='fiscal_year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='companyfact',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
