# Generated by Django 5.0.2 on 2024-12-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0021_alter_companyfact_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfact',
            name='frame',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
