# Generated by Django 5.0.2 on 2024-12-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0022_alter_companyfact_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfact',
            name='start_date',
        ),
    ]
