# Generated by Django 5.0.2 on 2024-12-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0023_remove_companyfact_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='cik',
            field=models.OneToOneField(db_column='cik', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedgar.company'),
        ),
    ]
