# Generated by Django 6.0.4 on 2026-04-11 11:32

import django.contrib.postgres.fields
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0024_alter_companyinfo_cik'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnalystDashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BulkFilingIndex',
            fields=[
                ('filename', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('quarter', models.IntegerField(db_index=True)),
                ('processed', models.DateField(db_index=True, default=False, null=True)),
                ('error', models.BooleanField(db_index=True, default=False)),
                ('ignored', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilingAnalysisPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('cik', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=1024)),
                ('form_type', models.CharField(max_length=64)),
                ('date_filed', models.DateField()),
                ('analysis_content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('ai_opinion', 2), ('supporting_fragment', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': "The LLM's primary conclusion."}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('section', 3), ('content', 4), ('has_table', 5)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SECIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='company',
            name='cusip',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='exchange',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='figi',
            field=models.CharField(blank=True, db_index=True, help_text='OpenFIGI Identifier', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='isin',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sic_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='filingdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchqueryresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchqueryterm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AnalystProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('coverage_industries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=list, help_text='List of SIC codes covered by this analyst.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Is this the lead analyst for this stock?')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='openedgar.analystprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.company')),
            ],
            options={
                'unique_together': {('analyst', 'company')},
            },
        ),
    ]
