# Generated by Django 6.0.4 on 2026-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0025_aboutpage_analystdashboardpage_bulkfilingindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='documents_index',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
