# Generated by Django 6.0.4 on 2026-04-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0026_filing_documents_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipSubmission',
            fields=[
                ('accession_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedgar.filing')),
                ('filing_date', models.DateField(db_index=True)),
                ('period_of_report', models.DateField(db_index=True, null=True)),
                ('issuer_name', models.CharField(max_length=1024)),
                ('issuer_trading_symbol', models.CharField(max_length=12, null=True)),
                ('form_type', models.CharField(max_length=10)),
                ('issuer_cik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_ownerships', to='openedgar.company')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipNonDerivTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.IntegerField()),
                ('rpt_owner_cik', models.BigIntegerField()),
                ('security_title', models.CharField(max_length=1024)),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_code', models.CharField(max_length=2, null=True)),
                ('transaction_shares', models.FloatField(null=True)),
                ('transaction_price_per_share', models.FloatField(null=True)),
                ('transaction_acquired_disposed_code', models.CharField(max_length=1, null=True)),
                ('shares_owned_following_transaction', models.FloatField(null=True)),
                ('direct_or_indirect_ownership', models.CharField(max_length=1, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_deriv_transactions', to='openedgar.ownershipsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipNonDerivHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.IntegerField()),
                ('rpt_owner_cik', models.BigIntegerField()),
                ('security_title', models.CharField(max_length=1024)),
                ('shares_owned_following_transaction', models.FloatField(null=True)),
                ('direct_or_indirect_ownership', models.CharField(max_length=1, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_deriv_holdings', to='openedgar.ownershipsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipDerivTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.IntegerField()),
                ('security_title', models.CharField(max_length=1024)),
                ('conversion_or_exercise_price', models.FloatField(null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_code', models.CharField(max_length=2, null=True)),
                ('exercise_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('underlying_security_title', models.CharField(max_length=1024, null=True)),
                ('underlying_security_shares', models.FloatField(null=True)),
                ('transaction_acquired_disposed_code', models.CharField(max_length=1, null=True)),
                ('shares_owned_following_transaction', models.FloatField(null=True)),
                ('direct_or_indirect_ownership', models.CharField(max_length=1, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deriv_transactions', to='openedgar.ownershipsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipDerivHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.IntegerField()),
                ('security_title', models.CharField(max_length=1024)),
                ('shares_owned_following_transaction', models.FloatField(null=True)),
                ('direct_or_indirect_ownership', models.CharField(max_length=1, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deriv_holdings', to='openedgar.ownershipsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipReportingOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpt_owner_cik', models.BigIntegerField(db_index=True)),
                ('rpt_owner_name', models.CharField(max_length=1024)),
                ('is_director', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_ten_percent_owner', models.BooleanField(default=False)),
                ('is_other', models.BooleanField(default=False)),
                ('officer_title', models.CharField(max_length=1024, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_owners', to='openedgar.ownershipsubmission')),
            ],
            options={
                'unique_together': {('submission', 'rpt_owner_cik')},
            },
        ),
        migrations.CreateModel(
            name='OwnershipFootnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footnote_id', models.CharField(max_length=10)),
                ('footnote_text', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='openedgar.ownershipsubmission')),
            ],
            options={
                'unique_together': {('submission', 'footnote_id')},
            },
        ),
    ]
