# Generated by Django 6.0.4 on 2026-04-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0027_ownershipsubmission_ownershipnonderivtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipderivholding',
            name='conversion_or_exercise_price_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='direct_or_indirect_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='exercise_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='expiration_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='nature_of_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='security_title_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='shares_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='underlying_security_shares_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='underlying_security_title_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='underlying_security_value_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='value_owned_following_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='conversion_or_exercise_price_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='deemed_execution_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='direct_or_indirect_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='exercise_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='expiration_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='nature_of_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='security_title_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='shares_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='transaction_acquired_disposed_code_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='transaction_code_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='transaction_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='transaction_timeliness_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='underlying_security_shares_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='underlying_security_title_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='underlying_security_value_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='value_owned_following_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='direct_or_indirect_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='nature_of_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='security_title_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='shares_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='value_owned_following_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='deemed_execution_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='direct_or_indirect_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='nature_of_ownership_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='security_title_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='shares_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_acquired_disposed_code_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_code_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_date_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_price_per_share_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_shares_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_timeliness_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_total_value_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='value_owned_following_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
