# Generated by Django 6.0.4 on 2026-04-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0028_ownershipderivholding_conversion_or_exercise_price_fn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownershipnonderivholding',
            old_name='rpt_owner_cik',
            new_name='rptowner_cik',
        ),
        migrations.RenameField(
            model_name='ownershipnonderivtransaction',
            old_name='rpt_owner_cik',
            new_name='rptowner_cik',
        ),
        migrations.RenameField(
            model_name='ownershipreportingowner',
            old_name='rpt_owner_cik',
            new_name='rptowner_cik',
        ),
        migrations.RenameField(
            model_name='ownershipreportingowner',
            old_name='rpt_owner_name',
            new_name='rptowner_name',
        ),
        migrations.AlterUniqueTogether(
            name='ownershipreportingowner',
            unique_together={('submission', 'rptowner_cik')},
        ),
    ]
