# Generated by Django 6.0.4 on 2026-04-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0029_rename_rpt_owner_cik_ownershipnonderivholding_rptowner_cik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownershipreportingowner',
            old_name='is_ten_percent_owner',
            new_name='is_10pctowner',
        ),
    ]
