# Generated by Django 6.0.4 on 2026-04-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0030_rename_is_ten_percent_owner_ownershipreportingowner_is_10pctowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_city',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_street1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_street2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OwnershipSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(max_length=1024)),
                ('signature_date', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='openedgar.ownershipsubmission')),
            ],
        ),
    ]
