# Generated by Django 6.0.4 on 2026-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0031_ownershipreportingowner_rptowner_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershipsubmission',
            name='issuer_trading_symbol',
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='transaction_form_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='deemed_execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='equity_swap_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='transaction_form_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='transaction_timeliness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='transaction_form_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='deemed_execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='equity_swap_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_form_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_timeliness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='is_director_nominee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='other_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='date_of_original_submission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='is_rule_10b5_1_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='no_securities_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='not_subject_to_section_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownershipsubmission',
            name='form_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ownershipsubmission',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
