# Generated by Django 6.0.4 on 2026-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0032_remove_ownershipsubmission_issuer_trading_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipsubmission',
            name='issuer_trading_symbol',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
