# Generated by Django 6.0.4 on 2026-04-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0033_ownershipsubmission_issuer_trading_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipderivholding',
            name='conversion_or_exercise_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='exercise_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='nature_of_ownership',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='underlying_security_shares',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='underlying_security_title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='underlying_security_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='value_owned_following_transaction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivholding',
            name='value_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='nature_of_ownership',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='underlying_security_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='value_owned_following_transaction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipderivtransaction',
            name='value_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='nature_of_ownership',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='value_owned_following_transaction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivholding',
            name='value_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='nature_of_ownership',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='transaction_total_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='value_owned_following_transaction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ownershipnonderivtransaction',
            name='value_owned_following_transaction_fn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_ccc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_country',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_good_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_non_us_address_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_non_us_state_territory',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipreportingowner',
            name='rptowner_state_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='issuer_foreign_trading_symbol',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ownershipsubmission',
            name='schema_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ownershipreportingowner',
            name='rptowner_cik',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
