# Generated by Django 6.0.4 on 2026-04-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0034_ownershipderivholding_conversion_or_exercise_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='day',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='markdown_path',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='month',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='qtr',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
