# Generated by Django 6.0.4 on 2026-06-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0035_filing_path_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipsubmission',
            name='accession_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedgar.filing'),
        ),
    ]
