# Generated by Django 6.0.4 on 2026-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0036_alter_ownershipsubmission_accession_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystprofile',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Your Anthropic API key (sk-ant-...). Required when provider is Claude.', max_length=255),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Your Google Gemini API key. Required when provider is Gemini.', max_length=255),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT-4o)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('groq', 'Groq (Fast Inference)')], default='openai', help_text='Which LLM provider to use for Q&A and report generation.', max_length=20),
        ),
        migrations.AddField(
            model_name='analystprofile',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Your OpenAI API key (sk-...). Required when provider is OpenAI.', max_length=255),
        ),
    ]
