import json

def get_ownership_extraction_prompt():
    """
    Canonical source of truth for SEC Ownership Extraction instructions.
    Used by both training (corpus generation) and evaluation (baseline passes).
    """
    schema_template = {
        "issuer": {"issuer_cik": "", "issuer_name": "", "issuer_trading_symbol": "", "issuer_foreign_trading_symbol": "", "schema_version": ""},
        "form_type": "", "period_of_report": "", "date_of_original_submission": "",
        "remarks": "", "not_subject_to_section_16": False, "is_rule_10b5_1_plan": False, "no_securities_owned": False,
        "reporting_owners": [{"rptowner_cik": "", "rptowner_name": "", "rptowner_ccc": "", "is_director": False, "is_officer": False, "is_10pctowner": False, "is_other": False, "other_text": "", "is_director_nominee": False, "officer_title": "", "rptowner_street1": "", "rptowner_street2": "", "rptowner_city": "", "rptowner_state": "", "rptowner_zip": "", "rptowner_non_us_address_flag": False, "rptowner_non_us_state_territory": "", "rptowner_country": "", "rptowner_state_description": "", "rptowner_good_address": False}],
        "non_derivative_transactions": [{"security_title": "", "security_title_fn": [], "transaction_date": "", "transaction_date_fn": [], "deemed_execution_date": "", "deemed_execution_date_fn": [], "transaction_code": "", "transaction_code_fn": [], "transaction_timeliness": "", "transaction_timeliness_fn": [], "transaction_form_type": "", "equity_swap_involved": False, "transaction_acquired_disposed_code": "", "transaction_acquired_disposed_code_fn": [], "shares": 0.0, "shares_fn": [], "price": 0.0, "price_fn": [], "transaction_total_value": 0.0, "transaction_total_value_fn": [], "shares_owned_following_transaction": 0.0, "shares_owned_following_transaction_fn": [], "value_owned_following_transaction": 0.0, "value_owned_following_transaction_fn": [], "direct_or_indirect_ownership": "", "direct_or_indirect_ownership_fn": [], "nature_of_ownership": "", "nature_of_ownership_fn": [], "transaction_summary": ""}],
        "non_derivative_holdings": [{"security_title": "", "security_title_fn": [], "shares_owned_following_transaction": 0.0, "shares_owned_following_transaction_fn": [], "value_owned_following_transaction": 0.0, "value_owned_following_transaction_fn": [], "direct_or_indirect_ownership": "", "direct_or_indirect_ownership_fn": [], "nature_of_ownership": "", "nature_of_ownership_fn": [], "transaction_form_type": ""}],
        "derivative_transactions": [{"security_title": "", "security_title_fn": [], "conversion_or_exercise_price": 0.0, "conversion_or_exercise_price_fn": [], "transaction_date": "", "transaction_date_fn": [], "deemed_execution_date": "", "deemed_execution_date_fn": [], "transaction_code": "", "transaction_code_fn": [], "transaction_timeliness": "", "transaction_timeliness_fn": [], "transaction_form_type": "", "equity_swap_involved": False, "transaction_acquired_disposed_code": "", "transaction_acquired_disposed_code_fn": [], "exercise_date": "", "exercise_date_fn": [], "expiration_date": "", "expiration_date_fn": [], "underlying_security_title": "", "underlying_security_title_fn": [], "underlying_security_shares": 0.0, "underlying_security_shares_fn": [], "underlying_security_value": 0.0, "underlying_security_value_fn": [], "shares_owned_following_transaction": 0.0, "shares_owned_following_transaction_fn": [], "value_owned_following_transaction": 0.0, "value_owned_following_transaction_fn": [], "direct_or_indirect_ownership": "", "direct_or_indirect_ownership_fn": [], "nature_of_ownership": "", "nature_of_ownership_fn": [], "transaction_summary": ""}],
        "derivative_holdings": [{"security_title": "", "security_title_fn": [], "conversion_or_exercise_price": 0.0, "conversion_or_exercise_price_fn": [], "exercise_date": "", "exercise_date_fn": [], "expiration_date": "", "expiration_date_fn": [], "underlying_security_title": "", "underlying_security_title_fn": [], "underlying_security_shares": 0.0, "underlying_security_shares_fn": [], "underlying_security_value": 0.0, "underlying_security_value_fn": [], "shares_owned_following_transaction": 0.0, "shares_owned_following_transaction_fn": [], "value_owned_following_transaction": 0.0, "value_owned_following_transaction_fn": [], "direct_or_indirect_ownership": "", "direct_or_indirect_ownership_fn": [], "nature_of_ownership": "", "nature_of_ownership_fn": [], "transaction_form_type": ""}],
        "footnotes": {"1": ""},
        "signatures": [{"signature_name": "", "signature_date": ""}]
    }

    prompt = (
        "You are a specialized SEC data extraction expert. Extract the provided SEC Ownership Filing into the following EXACT JSON structure:\n"
        f"{json.dumps(schema_template, indent=1)}\n\n"
        "CRITICAL RULES:\n"
        "1. Filing Metadata (YAML): Parse YAML frontmatter between --- markers. Map issuer_cik, issuer_name, issuer_trading_symbol, issuer_foreign_trading_symbol, schema_version into the issuer object. Map form_type, period_of_report, date_of_original_submission as top-level fields. Map not_subject_to_section_16, is_rule_10b5_1_plan, no_securities_owned as top-level booleans. Use empty string for missing text, false for missing booleans.\n"
        "2. Reporting Owners: Extract every owner. Populate ALL role booleans: is_director, is_officer, is_10pctowner, is_other, is_director_nominee. Populate other_text when is_other is true. Extract all address fields. Set rptowner_non_us_address_flag true for non-US addresses.\n"
        "3. Table I Transactions: Extract rows from the '## Table I - Non-Derivative Securities' section under the '### Transactions' sub-header. Map into non_derivative_transactions: Date→transaction_date, Deemed Exec→deemed_execution_date, Code→transaction_code, Form Type→transaction_form_type, A/D→transaction_acquired_disposed_code, Equity Swap→equity_swap_involved (bool), Timeliness→transaction_timeliness, Shares→shares, Price→price, Total Value→transaction_total_value. Extract inline [^N] markers into the *_fn arrays.\n"
        "4. Table I Holdings: Extract rows from the '## Table I - Non-Derivative Securities' section under the '### Holdings' sub-header. These are summary rows without transaction codes. DO NOT create a holding entry for the resulting balance of a transaction row.\n"
        "5. Table II Transactions: Extract rows from the '## Table II - Derivative Securities' section under the '### Transactions' sub-header. Map into derivative_transactions: all columns including conversion_or_exercise_price, transaction_date, deemed_execution_date, transaction_code, transaction_form_type, transaction_acquired_disposed_code, equity_swap_involved, transaction_timeliness, exercise_date, expiration_date, underlying_security_title, underlying_security_shares, underlying_security_value, shares_owned_following_transaction, value_owned_following_transaction, direct_or_indirect_ownership, nature_of_ownership.\n"
        "6. Table II Holdings: Extract rows from the '## Table II - Derivative Securities' section under the '### Holdings' sub-header. These are summary rows without transaction codes. DO NOT create a holding entry for the resulting balance of a transaction row.\n"
        "6b. Column Mapping Guardrail: In these markdown tables, D/I ownership values belong in direct_or_indirect_ownership. transaction_form_type should ALWAYS be the filing form number (e.g., 4 or 5), never 'D' or 'I'.\n"
        "7. Footnote References (*_fn fields): Every table cell can contain multiple inline references (e.g., [^1][^2]) and this is common, not an edge case. Capture ALL refs for that cell into the matching *_fn array as string IDs like ['1','2']. Never comma-separated strings. If none, return []. For numeric/text values, remove the inline markers from the value and keep refs only in the *_fn array.\n"
        "8. Footnotes Section: Extract all entries from '## Footnotes' into a dict {ID: full_text}. Strip leading 'F' from IDs. Preserve full text.\n"
        "9. Signatures: Extract every row from '## Signatures' table into signatures array with signature_name and signature_date.\n"
        "10. Booleans and Nullability: true/false for booleans. Empty string for missing text/dates. 0.0 for missing numerics. Never null.\n"
        "11. Address State Fields: Use standard two-letter U.S. state abbreviations (e.g., CA, NY) for state fields.\n"
        "12. Summaries: Provide transaction_summary for every transaction (not holdings) in natural language grounded only in the filing content.\n"
        "13. Output Contract: Return ONLY valid JSON in a single ```json block. Match schema keys exactly. No extra keys."
    )
    return prompt
